server:
  port : 8081

spring:
  datasource:
    url: jdbc:mysql://127.0.0.1/kiosk?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: root
    password: yr030709
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    open-in-view: false
    show-sql: true
    hibernate:
      ddl-auto: update
      use-new-id-generator-mapping: false

  jwt :
    header: Authorization
    secret: efnsoifh32y9t8y4rghefaseoifhosbxcjkvuiwrfhjweanbiv3892bvskjdvkjsbvriguhjdbqiasdhf9283GRERgjhfv3i9138NDVSIREg
    token-validity-in-seconds:
  mvc:
    locale:
      timezone: Asia/Seoul