spring:
  datasource:
    url: jdbc:mysql://125.133.34.224:33060/expo2024
    username: one
    password: one2024
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    open-in-view: false
    show-sql: true
    hibernate:
      ddl-auto: update
      use-new-id-generator-mapping: false

  jwt :
    header: Authorization
    secret: efnsoifh32y9t8y4rghefaseoifhosbxcjkvuiwrfhjweanbiv3892bvskjdvkjsbvriguhjdbqiasdhf9283GRERgjhfv3i9138NDVSIREg
    token-validity-in-seconds:
  mvc:
    locale:
      timezone: Asia/Seoul

  file:
    upload-dir: /home/pi/uploade_image

  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB
      max-request-size: 10MB
